-- Xóa dữ liệu cũ
DELETE FROM bms_system;

-- ============================================================
-- NHẬP DỮ LIỆU BMS SYSTEMS (Hệ thống Giám sát & Điều khiển)
-- ============================================================
INSERT INTO bms_system (system_type, system_name, location, status, current_value, unit, description) VALUES
('HVAC', 'Hệ thống điều hòa tầng 1', 'Tầng 1', 'NORMAL', 24.5, '°C', 'Hệ thống điều hòa không khí tầng 1'),
('ELECTRICAL', 'Tủ điện chính', 'Tầng hầm B1', 'NORMAL', 380, 'V', 'Tủ điện chính của tòa nhà'),
('PLUMBING', 'Hệ thống cấp nước', 'Tầng hầm B1', 'NORMAL', 3.5, 'bar', 'Hệ thống cấp nước sinh hoạt'),
('ELEVATOR', 'Thang máy số 1', 'Tầng 1', 'NORMAL', 1, 'tầng', 'Thang máy chở khách số 1'),
('SECURITY', 'Camera an ninh tầng 1', 'Tầng 1', 'NORMAL', 1, 'camera', 'Hệ thống camera giám sát'),
('FIRE_SAFETY', 'Hệ thống báo cháy', 'Toàn tòa nhà', 'NORMAL', 0, 'cảm biến', 'Hệ thống báo cháy tự động'),
('LIGHTING', 'Đèn chiếu sáng sảnh', 'Sảnh chính', 'NORMAL', 100, '%', 'Hệ thống đèn chiếu sáng'),
('WATER_SUPPLY', 'Bể nước trên mái', 'Sân thượng', 'NORMAL', 85, '%', 'Bể chứa nước sinh hoạt'),
('HVAC', 'Hệ thống điều hòa tầng 2', 'Tầng 2', 'NORMAL', 25.0, '°C', 'Hệ thống điều hòa không khí tầng 2'),
('ELECTRICAL', 'Tủ điện tầng 2', 'Tầng 2', 'NORMAL', 220, 'V', 'Tủ điện phân phối tầng 2'),
('PLUMBING', 'Hệ thống thoát nước', 'Tầng hầm B2', 'NORMAL', 0, 'm³/h', 'Hệ thống thoát nước thải'),
('ELEVATOR', 'Thang máy số 2', 'Tầng 1', 'NORMAL', 5, 'tầng', 'Thang máy chở khách số 2'),
('SECURITY', 'Camera an ninh tầng 2', 'Tầng 2', 'NORMAL', 1, 'camera', 'Hệ thống camera giám sát'),
('FIRE_SAFETY', 'Vòi phun nước tầng 1', 'Tầng 1', 'NORMAL', 0, 'vòi', 'Hệ thống phun nước chữa cháy'),
('LIGHTING', 'Đèn chiếu sáng hành lang', 'Hành lang tầng 1', 'NORMAL', 80, '%', 'Hệ thống đèn chiếu sáng'),
('WATER_SUPPLY', 'Máy bơm nước', 'Tầng hầm B1', 'NORMAL', 1, 'máy', 'Máy bơm cấp nước'),
('HVAC', 'Hệ thống điều hòa tầng 3', 'Tầng 3', 'NORMAL', 24.0, '°C', 'Hệ thống điều hòa không khí tầng 3'),
('ELECTRICAL', 'Tủ điện tầng 3', 'Tầng 3', 'NORMAL', 220, 'V', 'Tủ điện phân phối tầng 3'),
('PLUMBING', 'Hệ thống nước nóng', 'Tầng hầm B1', 'NORMAL', 60, '°C', 'Hệ thống cấp nước nóng'),
('ELEVATOR', 'Thang máy số 3', 'Tầng 1', 'NORMAL', 10, 'tầng', 'Thang máy chở hàng'),
('SECURITY', 'Camera an ninh tầng 3', 'Tầng 3', 'NORMAL', 1, 'camera', 'Hệ thống camera giám sát'),
('FIRE_SAFETY', 'Vòi phun nước tầng 2', 'Tầng 2', 'NORMAL', 0, 'vòi', 'Hệ thống phun nước chữa cháy'),
('LIGHTING', 'Đèn chiếu sáng cầu thang', 'Cầu thang bộ', 'NORMAL', 90, '%', 'Hệ thống đèn chiếu sáng'),
('WATER_SUPPLY', 'Bể nước dự phòng', 'Tầng hầm B2', 'NORMAL', 50, '%', 'Bể chứa nước dự phòng'),
('HVAC', 'Hệ thống điều hòa tầng 4', 'Tầng 4', 'NORMAL', 25.5, '°C', 'Hệ thống điều hòa không khí tầng 4'),
('ELECTRICAL', 'Tủ điện tầng 4', 'Tầng 4', 'NORMAL', 220, 'V', 'Tủ điện phân phối tầng 4'),
('PLUMBING', 'Hệ thống xử lý nước thải', 'Tầng hầm B2', 'NORMAL', 0, 'm³/h', 'Hệ thống xử lý nước thải'),
('ELEVATOR', 'Thang máy số 4', 'Tầng 1', 'NORMAL', 15, 'tầng', 'Thang máy chở khách số 3'),
('SECURITY', 'Camera an ninh tầng 4', 'Tầng 4', 'NORMAL', 1, 'camera', 'Hệ thống camera giám sát'),
('FIRE_SAFETY', 'Vòi phun nước tầng 3', 'Tầng 3', 'NORMAL', 0, 'vòi', 'Hệ thống phun nước chữa cháy'),
('LIGHTING', 'Đèn chiếu sáng bãi đỗ xe', 'Bãi đỗ xe', 'NORMAL', 70, '%', 'Hệ thống đèn chiếu sáng'),
('WATER_SUPPLY', 'Máy lọc nước', 'Tầng hầm B1', 'NORMAL', 1, 'máy', 'Hệ thống lọc nước'),
('HVAC', 'Hệ thống điều hòa tầng 5', 'Tầng 5', 'NORMAL', 24.8, '°C', 'Hệ thống điều hòa không khí tầng 5'),
('ELECTRICAL', 'Tủ điện tầng 5', 'Tầng 5', 'NORMAL', 220, 'V', 'Tủ điện phân phối tầng 5'),
('PLUMBING', 'Hệ thống tưới cây', 'Sân thượng', 'NORMAL', 0, 'm³/h', 'Hệ thống tưới cây tự động'),
('ELEVATOR', 'Thang máy số 5', 'Tầng 1', 'NORMAL', 20, 'tầng', 'Thang máy chở khách số 4'),
('SECURITY', 'Camera an ninh tầng 5', 'Tầng 5', 'NORMAL', 1, 'camera', 'Hệ thống camera giám sát'),
('FIRE_SAFETY', 'Vòi phun nước tầng 4', 'Tầng 4', 'NORMAL', 0, 'vòi', 'Hệ thống phun nước chữa cháy'),
('LIGHTING', 'Đèn chiếu sáng sân vườn', 'Sân vườn', 'NORMAL', 60, '%', 'Hệ thống đèn chiếu sáng'),
('WATER_SUPPLY', 'Bể nước tưới cây', 'Sân thượng', 'NORMAL', 30, '%', 'Bể chứa nước tưới cây'),
('HVAC', 'Hệ thống điều hòa tầng 6', 'Tầng 6', 'NORMAL', 25.2, '°C', 'Hệ thống điều hòa không khí tầng 6'),
('ELECTRICAL', 'Tủ điện tầng 6', 'Tầng 6', 'NORMAL', 220, 'V', 'Tủ điện phân phối tầng 6'),
('PLUMBING', 'Hệ thống nước uống', 'Tầng hầm B1', 'NORMAL', 0, 'm³/h', 'Hệ thống cấp nước uống'),
('ELEVATOR', 'Thang máy số 6', 'Tầng 1', 'NORMAL', 25, 'tầng', 'Thang máy chở khách số 5'),
('SECURITY', 'Camera an ninh tầng 6', 'Tầng 6', 'NORMAL', 1, 'camera', 'Hệ thống camera giám sát'),
('FIRE_SAFETY', 'Vòi phun nước tầng 5', 'Tầng 5', 'NORMAL', 0, 'vòi', 'Hệ thống phun nước chữa cháy'),
('LIGHTING', 'Đèn chiếu sáng phòng kỹ thuật', 'Phòng kỹ thuật', 'NORMAL', 100, '%', 'Hệ thống đèn chiếu sáng'),
('WATER_SUPPLY', 'Máy bơm tăng áp', 'Tầng hầm B1', 'NORMAL', 1, 'máy', 'Máy bơm tăng áp nước'),
('HVAC', 'Hệ thống điều hòa tầng 7', 'Tầng 7', 'NORMAL', 24.3, '°C', 'Hệ thống điều hòa không khí tầng 7'),
('ELECTRICAL', 'Tủ điện tầng 7', 'Tầng 7', 'NORMAL', 220, 'V', 'Tủ điện phân phối tầng 7'),
('PLUMBING', 'Hệ thống nước thải', 'Tầng hầm B2', 'NORMAL', 0, 'm³/h', 'Hệ thống thoát nước thải'),
('ELEVATOR', 'Thang máy số 7', 'Tầng 1', 'NORMAL', 30, 'tầng', 'Thang máy chở khách số 6'),
('SECURITY', 'Camera an ninh tầng 7', 'Tầng 7', 'NORMAL', 1, 'camera', 'Hệ thống camera giám sát'),
('FIRE_SAFETY', 'Vòi phun nước tầng 6', 'Tầng 6', 'NORMAL', 0, 'vòi', 'Hệ thống phun nước chữa cháy'),
('LIGHTING', 'Đèn chiếu sáng tầng hầm', 'Tầng hầm B1', 'NORMAL', 75, '%', 'Hệ thống đèn chiếu sáng'),
('WATER_SUPPLY', 'Bể nước sinh hoạt', 'Tầng hầm B1', 'NORMAL', 90, '%', 'Bể chứa nước sinh hoạt'),
('HVAC', 'Hệ thống điều hòa tầng 8', 'Tầng 8', 'NORMAL', 25.0, '°C', 'Hệ thống điều hòa không khí tầng 8'),
('ELECTRICAL', 'Tủ điện tầng 8', 'Tầng 8', 'NORMAL', 220, 'V', 'Tủ điện phân phối tầng 8'),
('PLUMBING', 'Hệ thống cấp nước tầng cao', 'Tầng 8', 'NORMAL', 2.5, 'bar', 'Hệ thống cấp nước tầng cao'),
('ELEVATOR', 'Thang máy số 8', 'Tầng 1', 'NORMAL', 35, 'tầng', 'Thang máy chở khách số 7'),
('SECURITY', 'Camera an ninh tầng 8', 'Tầng 8', 'NORMAL', 1, 'camera', 'Hệ thống camera giám sát'),
('FIRE_SAFETY', 'Vòi phun nước tầng 7', 'Tầng 7', 'NORMAL', 0, 'vòi', 'Hệ thống phun nước chữa cháy'),
('LIGHTING', 'Đèn chiếu sáng tầng hầm B2', 'Tầng hầm B2', 'NORMAL', 65, '%', 'Hệ thống đèn chiếu sáng'),
('WATER_SUPPLY', 'Máy bơm nước thải', 'Tầng hầm B2', 'NORMAL', 1, 'máy', 'Máy bơm nước thải'),
('HVAC', 'Hệ thống điều hòa tầng 9', 'Tầng 9', 'NORMAL', 24.6, '°C', 'Hệ thống điều hòa không khí tầng 9'),
('ELECTRICAL', 'Tủ điện tầng 9', 'Tầng 9', 'NORMAL', 220, 'V', 'Tủ điện phân phối tầng 9'),
('PLUMBING', 'Hệ thống nước mưa', 'Sân thượng', 'NORMAL', 0, 'm³/h', 'Hệ thống thu gom nước mưa'),
('ELEVATOR', 'Thang máy số 9', 'Tầng 1', 'NORMAL', 40, 'tầng', 'Thang máy chở khách số 8'),
('SECURITY', 'Camera an ninh tầng 9', 'Tầng 9', 'NORMAL', 1, 'camera', 'Hệ thống camera giám sát'),
('FIRE_SAFETY', 'Vòi phun nước tầng 8', 'Tầng 8', 'NORMAL', 0, 'vòi', 'Hệ thống phun nước chữa cháy'),
('LIGHTING', 'Đèn chiếu sáng sảnh phụ', 'Sảnh phụ', 'NORMAL', 85, '%', 'Hệ thống đèn chiếu sáng'),
('WATER_SUPPLY', 'Bể nước dự trữ', 'Tầng hầm B2', 'NORMAL', 40, '%', 'Bể chứa nước dự trữ'),
('HVAC', 'Hệ thống điều hòa tầng 10', 'Tầng 10', 'NORMAL', 25.1, '°C', 'Hệ thống điều hòa không khí tầng 10'),
('ELECTRICAL', 'Tủ điện tầng 10', 'Tầng 10', 'NORMAL', 220, 'V', 'Tủ điện phân phối tầng 10'),
('PLUMBING', 'Hệ thống nước cứu hỏa', 'Toàn tòa nhà', 'NORMAL', 5.0, 'bar', 'Hệ thống nước cứu hỏa'),
('ELEVATOR', 'Thang máy số 10', 'Tầng 1', 'NORMAL', 45, 'tầng', 'Thang máy chở khách số 9'),
('SECURITY', 'Camera an ninh tầng 10', 'Tầng 10', 'NORMAL', 1, 'camera', 'Hệ thống camera giám sát'),
('FIRE_SAFETY', 'Vòi phun nước tầng 9', 'Tầng 9', 'NORMAL', 0, 'vòi', 'Hệ thống phun nước chữa cháy'),
('LIGHTING', 'Đèn chiếu sáng khu vực chờ', 'Khu vực chờ', 'NORMAL', 95, '%', 'Hệ thống đèn chiếu sáng'),
('WATER_SUPPLY', 'Máy bơm cứu hỏa', 'Tầng hầm B1', 'NORMAL', 1, 'máy', 'Máy bơm nước cứu hỏa'),
('HVAC', 'Hệ thống điều hòa tầng 11', 'Tầng 11', 'NORMAL', 24.9, '°C', 'Hệ thống điều hòa không khí tầng 11'),
('ELECTRICAL', 'Tủ điện tầng 11', 'Tầng 11', 'NORMAL', 220, 'V', 'Tủ điện phân phối tầng 11'),
('PLUMBING', 'Hệ thống nước tái chế', 'Tầng hầm B2', 'NORMAL', 0, 'm³/h', 'Hệ thống xử lý nước tái chế'),
('ELEVATOR', 'Thang máy số 11', 'Tầng 1', 'NORMAL', 50, 'tầng', 'Thang máy chở khách số 10'),
('SECURITY', 'Camera an ninh tầng 11', 'Tầng 11', 'NORMAL', 1, 'camera', 'Hệ thống camera giám sát'),
('FIRE_SAFETY', 'Vòi phun nước tầng 10', 'Tầng 10', 'NORMAL', 0, 'vòi', 'Hệ thống phun nước chữa cháy'),
('LIGHTING', 'Đèn chiếu sáng phòng máy', 'Phòng máy', 'NORMAL', 100, '%', 'Hệ thống đèn chiếu sáng'),
('WATER_SUPPLY', 'Bể nước cứu hỏa', 'Sân thượng', 'NORMAL', 100, '%', 'Bể chứa nước cứu hỏa'),
('HVAC', 'Hệ thống điều hòa tầng 12', 'Tầng 12', 'NORMAL', 25.3, '°C', 'Hệ thống điều hòa không khí tầng 12'),
('ELECTRICAL', 'Tủ điện tầng 12', 'Tầng 12', 'NORMAL', 220, 'V', 'Tủ điện phân phối tầng 12'),
('PLUMBING', 'Hệ thống nước làm mát', 'Tầng hầm B1', 'NORMAL', 15, '°C', 'Hệ thống nước làm mát'),
('ELEVATOR', 'Thang máy số 12', 'Tầng 1', 'NORMAL', 55, 'tầng', 'Thang máy chở khách số 11'),
('SECURITY', 'Camera an ninh tầng 12', 'Tầng 12', 'NORMAL', 1, 'camera', 'Hệ thống camera giám sát'),
('FIRE_SAFETY', 'Vòi phun nước tầng 11', 'Tầng 11', 'NORMAL', 0, 'vòi', 'Hệ thống phun nước chữa cháy'),
('LIGHTING', 'Đèn chiếu sáng khu vực dịch vụ', 'Khu vực dịch vụ', 'NORMAL', 80, '%', 'Hệ thống đèn chiếu sáng'),
('WATER_SUPPLY', 'Máy lọc nước RO', 'Tầng hầm B1', 'NORMAL', 1, 'máy', 'Hệ thống lọc nước RO'),
('HVAC', 'Hệ thống điều hòa tầng 13', 'Tầng 13', 'NORMAL', 24.7, '°C', 'Hệ thống điều hòa không khí tầng 13'),
('ELECTRICAL', 'Tủ điện tầng 13', 'Tầng 13', 'NORMAL', 220, 'V', 'Tủ điện phân phối tầng 13'),
('PLUMBING', 'Hệ thống nước tinh khiết', 'Tầng hầm B1', 'NORMAL', 0, 'm³/h', 'Hệ thống cấp nước tinh khiết'),
('ELEVATOR', 'Thang máy số 13', 'Tầng 1', 'NORMAL', 60, 'tầng', 'Thang máy chở khách số 12'),
('SECURITY', 'Camera an ninh tầng 13', 'Tầng 13', 'NORMAL', 1, 'camera', 'Hệ thống camera giám sát'),
('FIRE_SAFETY', 'Vòi phun nước tầng 12', 'Tầng 12', 'NORMAL', 0, 'vòi', 'Hệ thống phun nước chữa cháy'),
('LIGHTING', 'Đèn chiếu sáng khu vực giải trí', 'Khu vực giải trí', 'NORMAL', 70, '%', 'Hệ thống đèn chiếu sáng'),
('WATER_SUPPLY', 'Bể nước tinh khiết', 'Tầng hầm B1', 'NORMAL', 60, '%', 'Bể chứa nước tinh khiết'),
('HVAC', 'Hệ thống điều hòa tầng 14', 'Tầng 14', 'NORMAL', 25.4, '°C', 'Hệ thống điều hòa không khí tầng 14'),
('ELECTRICAL', 'Tủ điện tầng 14', 'Tầng 14', 'NORMAL', 220, 'V', 'Tủ điện phân phối tầng 14'),
('PLUMBING', 'Hệ thống nước nóng trung tâm', 'Tầng hầm B1', 'NORMAL', 65, '°C', 'Hệ thống cấp nước nóng trung tâm'),
('ELEVATOR', 'Thang máy số 14', 'Tầng 1', 'NORMAL', 65, 'tầng', 'Thang máy chở khách số 13'),
('SECURITY', 'Camera an ninh tầng 14', 'Tầng 14', 'NORMAL', 1, 'camera', 'Hệ thống camera giám sát'),
('FIRE_SAFETY', 'Vòi phun nước tầng 13', 'Tầng 13', 'NORMAL', 0, 'vòi', 'Hệ thống phun nước chữa cháy'),
('LIGHTING', 'Đèn chiếu sáng khu vực thư viện', 'Khu vực thư viện', 'NORMAL', 90, '%', 'Hệ thống đèn chiếu sáng'),
('WATER_SUPPLY', 'Máy bơm nước nóng', 'Tầng hầm B1', 'NORMAL', 1, 'máy', 'Máy bơm nước nóng'),
('HVAC', 'Hệ thống điều hòa tầng 15', 'Tầng 15', 'NORMAL', 24.4, '°C', 'Hệ thống điều hòa không khí tầng 15'),
('ELECTRICAL', 'Tủ điện tầng 15', 'Tầng 15', 'NORMAL', 220, 'V', 'Tủ điện phân phối tầng 15'),
('PLUMBING', 'Hệ thống nước thải sinh hoạt', 'Tầng hầm B2', 'NORMAL', 0, 'm³/h', 'Hệ thống xử lý nước thải sinh hoạt'),
('ELEVATOR', 'Thang máy số 15', 'Tầng 1', 'NORMAL', 70, 'tầng', 'Thang máy chở khách số 14'),
('SECURITY', 'Camera an ninh tầng 15', 'Tầng 15', 'NORMAL', 1, 'camera', 'Hệ thống camera giám sát'),
('FIRE_SAFETY', 'Vòi phun nước tầng 14', 'Tầng 14', 'NORMAL', 0, 'vòi', 'Hệ thống phun nước chữa cháy'),
('LIGHTING', 'Đèn chiếu sáng khu vực thể thao', 'Khu vực thể thao', 'NORMAL', 75, '%', 'Hệ thống đèn chiếu sáng'),
('WATER_SUPPLY', 'Bể nước nóng', 'Tầng hầm B1', 'NORMAL', 75, '%', 'Bể chứa nước nóng'),
('HVAC', 'Hệ thống điều hòa tầng 16', 'Tầng 16', 'NORMAL', 25.6, '°C', 'Hệ thống điều hòa không khí tầng 16'),
('ELECTRICAL', 'Tủ điện tầng 16', 'Tầng 16', 'NORMAL', 220, 'V', 'Tủ điện phân phối tầng 16'),
('PLUMBING', 'Hệ thống nước mưa tái sử dụng', 'Sân thượng', 'NORMAL', 0, 'm³/h', 'Hệ thống thu gom và tái sử dụng nước mưa'),
('ELEVATOR', 'Thang máy số 16', 'Tầng 1', 'NORMAL', 75, 'tầng', 'Thang máy chở khách số 15'),
('SECURITY', 'Camera an ninh tầng 16', 'Tầng 16', 'NORMAL', 1, 'camera', 'Hệ thống camera giám sát'),
('FIRE_SAFETY', 'Vòi phun nước tầng 15', 'Tầng 15', 'NORMAL', 0, 'vòi', 'Hệ thống phun nước chữa cháy'),
('LIGHTING', 'Đèn chiếu sáng khu vực họp', 'Khu vực họp', 'NORMAL', 100, '%', 'Hệ thống đèn chiếu sáng'),
('WATER_SUPPLY', 'Máy bơm nước mưa', 'Sân thượng', 'NORMAL', 1, 'máy', 'Máy bơm nước mưa tái sử dụng'),
('HVAC', 'Hệ thống điều hòa tầng 17', 'Tầng 17', 'NORMAL', 24.2, '°C', 'Hệ thống điều hòa không khí tầng 17'),
('ELECTRICAL', 'Tủ điện tầng 17', 'Tầng 17', 'NORMAL', 220, 'V', 'Tủ điện phân phối tầng 17'),
('PLUMBING', 'Hệ thống nước uống tinh khiết', 'Tầng hầm B1', 'NORMAL', 0, 'm³/h', 'Hệ thống cấp nước uống tinh khiết'),
('ELEVATOR', 'Thang máy số 17', 'Tầng 1', 'NORMAL', 80, 'tầng', 'Thang máy chở khách số 16'),
('SECURITY', 'Camera an ninh tầng 17', 'Tầng 17', 'NORMAL', 1, 'camera', 'Hệ thống camera giám sát'),
('FIRE_SAFETY', 'Vòi phun nước tầng 16', 'Tầng 16', 'NORMAL', 0, 'vòi', 'Hệ thống phun nước chữa cháy'),
('LIGHTING', 'Đèn chiếu sáng khu vực văn phòng', 'Khu vực văn phòng', 'NORMAL', 95, '%', 'Hệ thống đèn chiếu sáng'),
('WATER_SUPPLY', 'Bể nước mưa', 'Sân thượng', 'NORMAL', 20, '%', 'Bể chứa nước mưa'),
('HVAC', 'Hệ thống điều hòa tầng 18', 'Tầng 18', 'NORMAL', 25.7, '°C', 'Hệ thống điều hòa không khí tầng 18'),
('ELECTRICAL', 'Tủ điện tầng 18', 'Tầng 18', 'NORMAL', 220, 'V', 'Tủ điện phân phối tầng 18'),
('PLUMBING', 'Hệ thống nước thải công nghiệp', 'Tầng hầm B2', 'NORMAL', 0, 'm³/h', 'Hệ thống xử lý nước thải công nghiệp'),
('ELEVATOR', 'Thang máy số 18', 'Tầng 1', 'NORMAL', 85, 'tầng', 'Thang máy chở khách số 17'),
('SECURITY', 'Camera an ninh tầng 18', 'Tầng 18', 'NORMAL', 1, 'camera', 'Hệ thống camera giám sát'),
('FIRE_SAFETY', 'Vòi phun nước tầng 17', 'Tầng 17', 'NORMAL', 0, 'vòi', 'Hệ thống phun nước chữa cháy'),
('LIGHTING', 'Đèn chiếu sáng khu vực ăn uống', 'Khu vực ăn uống', 'NORMAL', 85, '%', 'Hệ thống đèn chiếu sáng'),
('WATER_SUPPLY', 'Máy bơm nước tinh khiết', 'Tầng hầm B1', 'NORMAL', 1, 'máy', 'Máy bơm nước tinh khiết'),
('HVAC', 'Hệ thống điều hòa tầng 19', 'Tầng 19', 'NORMAL', 24.1, '°C', 'Hệ thống điều hòa không khí tầng 19'),
('ELECTRICAL', 'Tủ điện tầng 19', 'Tầng 19', 'NORMAL', 220, 'V', 'Tủ điện phân phối tầng 19'),
('PLUMBING', 'Hệ thống nước làm mát máy lạnh', 'Tầng hầm B1', 'NORMAL', 12, '°C', 'Hệ thống nước làm mát máy lạnh'),
('ELEVATOR', 'Thang máy số 19', 'Tầng 1', 'NORMAL', 90, 'tầng', 'Thang máy chở khách số 18'),
('SECURITY', 'Camera an ninh tầng 19', 'Tầng 19', 'NORMAL', 1, 'camera', 'Hệ thống camera giám sát'),
('FIRE_SAFETY', 'Vòi phun nước tầng 18', 'Tầng 18', 'NORMAL', 0, 'vòi', 'Hệ thống phun nước chữa cháy'),
('LIGHTING', 'Đèn chiếu sáng khu vực nghỉ ngơi', 'Khu vực nghỉ ngơi', 'NORMAL', 50, '%', 'Hệ thống đèn chiếu sáng'),
('WATER_SUPPLY', 'Bể nước tinh khiết dự phòng', 'Tầng hầm B1', 'NORMAL', 55, '%', 'Bể chứa nước tinh khiết dự phòng'),
('HVAC', 'Hệ thống điều hòa tầng 20', 'Tầng 20', 'NORMAL', 25.8, '°C', 'Hệ thống điều hòa không khí tầng 20'),
('ELECTRICAL', 'Tủ điện tầng 20', 'Tầng 20', 'NORMAL', 220, 'V', 'Tủ điện phân phối tầng 20'),
('PLUMBING', 'Hệ thống nước thải xử lý', 'Tầng hầm B2', 'NORMAL', 0, 'm³/h', 'Hệ thống xử lý nước thải'),
('ELEVATOR', 'Thang máy số 20', 'Tầng 1', 'NORMAL', 95, 'tầng', 'Thang máy chở khách số 19'),
('SECURITY', 'Camera an ninh tầng 20', 'Tầng 20', 'NORMAL', 1, 'camera', 'Hệ thống camera giám sát'),
('FIRE_SAFETY', 'Vòi phun nước tầng 19', 'Tầng 19', 'NORMAL', 0, 'vòi', 'Hệ thống phun nước chữa cháy'),
('LIGHTING', 'Đèn chiếu sáng khu vực hành chính', 'Khu vực hành chính', 'NORMAL', 100, '%', 'Hệ thống đèn chiếu sáng'),
('WATER_SUPPLY', 'Máy bơm nước làm mát', 'Tầng hầm B1', 'NORMAL', 1, 'máy', 'Máy bơm nước làm mát máy lạnh');
